### ISSUE TITLE
More hardcoded symbols

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#105]
This is one of the goals of the third iteration.

Related: #104

**Comment by michal7352** [comment]
It's largely about file organisation. Each symbol traning-sample should be saved in file, and also 'tolerance distances' will be rather different for different symbols. To estimate the similarity to some symbol, I would consider doing separate nn-model for each symbol (and one big nn-model with all symbol samples, for classyfing to the best symbol).
