### ISSUE TITLE
Implement a CLI for the app

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#106]
This is one of the goals of the 4th iteration.

- [x] Define what the CLI is.
- [x] What will the CLI be for our app?

 Are command line arguments considered a CLI?

**Comment by 0mp** [comment]
Probably related: #71.

**Comment by piotrekp1** [comment]
we could make use of matrix analyser and let app draw specific learned symbol when someone asks for it

**Comment by 0mp** [comment]
@piotrekp1. This is a good idea - I thought about it some time ago. I guess it requires a separate issue though since it is not related to the command line interface.

**Comment by piotrekp1** [comment]
It depends on how we want to draw it, if we want to just draw the collected points it really belongs here, because most of the work is in conneting it with CLI, if we want to draw a pretty picture with connected points, yeah, then it definitely deserves to be another issue.

**Comment by 0mp** [comment]
@piotrekp1 You cannot show figures generated by the matrix analyser in the console. CLI is a command line interface - it's entirely text-based.

**Comment by piotrekp1** [comment]
and it cannot involve launching window with a picture?

**Comment by 0mp** [comment]
@piotrekp1 Well, we might add a command line option like "--show-figure" which shows a window with the symbol which have just been added.

**Comment by 0mp** [comment]
OK, let's assume that the CLI in out case is just a set of nice command line arguments.

I'll take care of this issue during this iteration - I'll add new command linen arguments to manage new features from #151.

**Comment by piotrekp1** [comment]
if you want to draw the designated symbol with sharps for example, i could do it, i thought about and i think i have a pretty simple idea that should work.

**Comment by 0mp** [comment]
1. Was is a _designated symbol_? What are _sharps_?
2. I don't want to draw anything. Implementing the CLI includes adding additional command line options only.

**Comment by piotrekp1** [comment]
i mean if you would like to "draw" a picture in terminal for example like that 

-#---
#-# #
---## just bigger, where sharps (#) represents a line of a symbol

**Comment by 0mp** [comment]
Oh. This is a pretty nice idea. We can try to implement it if we have some time left.

**Comment by 0mp** [comment]
I am going to refactor the current interface and add those command line options to the app:

Feature | Command line option | Comments
---|---|---
Add a new symbol.  | `add SIZE SYMBOL` | It is just a renamed `learn SIZE SYMBOL`.
Delete an existing symbol. | `delete SYMBOL` |
Activate an existing symbol. | `activate SYMBOL` | I think that `actiavte` sounds better than `turnon`
Deactivate an existing symbol. | `deactivate SYMBOL` |
List all the existing symbols. | `list` |
Modify the command of a symbol. | `modify SYMBOL COMMAND` | For e.g. `modify small-k 'touch /tmp/xyz`.
