### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#112]

**Comment by 0mp** [comment]
https://en.wikipedia.org/wiki/4%2B1_architectural_view_model

**Comment by 0mp** [comment]
- [ ] Focus on the logical view.

**Comment by RjiukYagami** [comment]
https://www.cs.ubc.ca/~gregor/teaching/papers/4+1view-architecture.pdf

**Comment by 0mp** [comment]
https://github.com/0mp/io-touchpad/wiki/Documentation:-Know%E2%80%90how

**Comment by RjiukYagami** [comment]
https://github.com/0mp/io-touchpad/wiki/Documentation:-Architecture

Done architecture.
