### ISSUE TITLE
Tests are modifying the app/test/classifier/data/user-defined/nn-model.dat

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#117]
Is it possible to prevent the tests from modifying the `app/test/classifier/data/user-defined/nn-model.dat` file during tests?

Or at least make the test module undo any changes after testing? 

It is rather annoying to `git checkout --` this file every time.

**Comment by michal7352** [comment]
I thought they didn't. They should not modify.

**Comment by RjiukYagami** [comment]
I have to talk this through with @michal7352  because it seems like test have to change this data when it learn from file.

**Comment by RjiukYagami** [comment]
Problem is not existing anymore.
