### ISSUE TITLE
What are we going to do with the touchpadsignal.TouchpadSignal.is_stop_signal method?

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#121]
Do you have any plans regarding this method?

https://landscape.io/github/0mp/io-touchpad/179/modules/app/touchpadsignal/touchpadsignal.py#L64

**Comment by michal7352** [comment]
I see this way: We're doing option for user, to draw figure stopped by raising finger. In this mode is_stopi_signal_function will be equal to raise_finger_option.

**Comment by 0mp** [comment]
@michal7352 This is a nice idea. I'll assign it to the respective iteration.

**Comment by michal7352** [comment]
Notice that the application thread, is already coded taking the stop-signals into account, so the job is only to define is_stop_signal, or keeping there "return False".
