### ISSUE TITLE
featureextractor refactoring

### ISSUE THREAD

**Issue by michal7352** [0mp/io-touchpad#123]
In my opinion:
- Methods computing mass centre, max/min X/Y,  and scaling function, should be moved to one class responsible for scaling (normalizing :) ) - constructor of this class would take list of points as a parameter.
It will be convenient when we have two feature-extractors using some common functions.

- It could be better if featureextractor was s class , not just a module. Then we could easily extend functionality, and for example we would be able to construct the extractor with some parametres, we would send training sample to the extractor and the extractor would decide on his own about scaling features according to disperse in the training-set, and so on...

**Comment by 0mp** [comment]
Additinally, Landscape shows that the refactoring is reaaally needed: 

![Score: Critical 3%](https://imgur.com/CZCIMz5.png)
