### ISSUE TITLE
Fix use cases

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#148]
- [x] Use cases should be self-contained.
- [x] Include a little dictionary to explain what words like _command_ or _symbol_ mean in our project.
- [x] Use cases should not be about the interaction with the UI.
- [x] New UML diagram.(Emil)

**Comment by 0mp** [comment]
Helpful links: https://github.com/0mp/io-touchpad/wiki/Documentation:-Know%E2%80%90how#use-cases

**Comment by 0mp** [comment]
Wiki page: https://github.com/0mp/io-touchpad/wiki/Documentation:-Use-cases

**Comment by RjiukYagami** [comment]
Link to use-cases : https://docs.google.com/document/d/1GeNCTt9GOW0BI-MLfgnJfpmsCCEX9nfeICCWMj1eoHc/edit?usp=sharing
