### ISSUE TITLE
Change the scope of the fifth iteration

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#149]
I think we are not able to produce a nice GUI in just a week. I'd change the scope of the 5<sup>th</sup> iteration and focus on the app's performance and bugs instead of GUI (#111).

However #112 has to be done no matter what.

I strongly suggest that we focus on these things during the 5<sup>th</sup> iteration:
- Find out why our app is using up to 100% of the CPU.
- Solve the bugs related issues.
- Improve the tests module.

What do you think?

![what do you think?](http://66.media.tumblr.com/b2d0f2957616ba6644b1a283d383d0d2/tumblr_n15k4b0mqt1qju2gio1_400.gif)

**Comment by michal7352** [comment]
We could finally do the "stop signal" on just raising finger option.
