### ISSUE TITLE
Deactivate symbols on the classifier level instead of the executor level

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#166]
At the moment the deactivated symbol is still recognizable by the app. It'd be cool if we can hide inactive symbols from the classifier.

Relates features introduced in #162.

**Comment by michal7352** [comment]
Deactivating in the classifier symbol list instead of databox level.... It's possible. But why should we do that ?

**Comment by 0mp** [comment]
@michal7352 The user might have two versions of one symbol with different commands.

**Comment by michal7352** [comment]
Still don't understand what you are going to do here. When user have two versions of one symbol with different commands... now it's not possible, so how do you see it and what deactivating should really do ?

**Comment by 0mp** [comment]
You have two symbols which look exactly the same: `k-firefox` and `k-chrome`. They open respective browsers when detected. 

You deactivate `k-firefox` and activate `k-chrome`. You expect that Chrome will launch when you draw _k_. This is why you cannot have `k-firefox` to be recognisable by the classifier.

Am I right?

**Comment by michal7352** [comment]
It's strange to have two separate identical symbols.... Maybe just the command should change in this case.

**Comment by michal7352** [comment]
But I see the sense of this in general. We don't want deactivated symbols to disturb in detecting similar active symbols. So it is to do,  but   deactivating in classifier means re-building the model (see _delete_symbol() function), and we have to remember in for example symbol_list file which symbols are currently active and which not.

**Comment by 0mp** [comment]
> It's strange to have two separate identical symbols.... Maybe just the command should change in this case.

I disagree. It should be perfectly fine to have multiple similar versions of a symbol with different commands.

Here's another scenario: you use this app when you work and in your free time. You have your favourite set of symbols (let's say: _k_, _a_, _b_, _w_) and you just switch want to switch the set of commands they trigger when you finish working.

It is much easier to type 

    ./app.py deactivate -s work-k work-a work-b work-w
    ./app.py activate -s free-k free-a free-b free-w

than

    ./app.py modify k ...
    ./app.py modify a ...
    ./app.py modify b ...
    ./app.py modify w ...

---

> deactivating in classifier means re-building the model

This is totally fine in my opinion. It doesn't take much time and will make the app more efficient.

**Comment by 0mp** [comment]
We didn't manage to finish it during the fifth iteration.
