### ISSUE TITLE
Tests for new subcommands

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#167]
#162 introduced a lot of new features.

We should create unit tests for all of them.

**Comment by RjiukYagami** [comment]
I wish someone could list me functionality to test. I see this functionality but which should i test?
@michal7352

**Comment by 0mp** [comment]
I guess you are looking for the subcommands listed here: https://github.com/0mp/io-touchpad/wiki/Summary:-v0.4%E2%80%90beta-(The-fourth-iteration)#cli-0mp.

You can list the subcommands using `./app.py -h` or just by looking into the app.py file.

**Comment by RjiukYagami** [comment]
All of the functionality used in function which are invoked with commands, are tested. Especially _test_databox_ covers it.
