### ISSUE TITLE
Create a test suite for the second iteration

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#22]
- Test the symbol detection system.
- Test the application after implementing new features.

**Comment by 0mp** [comment]
This might be helpful: https://www.freedesktop.org/wiki/Evemu/

**Comment by 0mp** [comment]
You might consider using one of these as well: https://github.com/integrations/feature/code

**Comment by 0mp** [comment]
https://travis-ci.org/

**Comment by 0mp** [comment]
I'll try to configure travis-ci.

**Comment by 0mp** [comment]
@RjiukYagami look at #78. I've managed to configure Travis CI. It looks like there are bugs in your tests.

**Comment by 0mp** [comment]
Travis CI is working now.

**Comment by 0mp** [comment]
#82

**Comment by RjiukYagami** [comment]
Tests to do

Checklist : 
- Classfier
- Executor
- Matrix-analyser
- Threads (imo not needed/to check)
- Databox

**Comment by 0mp** [comment]
@michal7352, @piotrekp1 can you help @RjiukYagami to create a test file for the classifier module?
