### ISSUE TITLE
Clean up touchpadlib.c

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#28]
There is a lot of code that could be removed. 

Just be careful when you remove those defines!

**Comment by 0mp** [comment]
Lenovo G500 touchpad events:

```
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0xe version 0x0
Input device name: "ETPS/2 Elantech Touchpad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   1230
      Min        0
      Max     2940
      Resolution      31
    Event code 1 (ABS_Y)
      Value    791
      Min        0
      Max     1260
      Resolution      31
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        1
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     2940
      Resolution      31
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1260
      Resolution      31
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 0 (INPUT_PROP_POINTER)
  Property type 3 (INPUT_PROP_SEMI_MT)
```

**Comment by 0mp** [comment]
Hasee Q540S touchpad events:
```
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0x7 version 0x1b1
Input device name: "SynPS/2 Synaptics TouchPad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   2225
      Min     1472
      Max     5472
      Resolution      57
    Event code 1 (ABS_Y)
      Value   3647
      Min     1408
      Max     4448
      Resolution      84
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
Properties:
  Property type 0 (INPUT_PROP_POINTER)
```

**Comment by michal7352** [comment]
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0xe version 0x0
Input device name: "ETPS/2 Elantech Touchpad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value    276
      Min        0
      Max     2508
    Event code 1 (ABS_Y)
      Value    828
      Min        0
      Max     1320
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        1
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     2508
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1320
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 0 (INPUT_PROP_POINTER)

**Comment by RjiukYagami** [comment]
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0xe version 0x0
Input device name: "ETPS/2 Elantech Touchpad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   2650
      Min        0
      Max     2940
      Resolution      31
    Event code 1 (ABS_Y)
      Value     93
      Min        0
      Max     1260
      Resolution      31
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        1
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     2940
      Resolution      31
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1260
      Resolution      31
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 0 (INPUT_PROP_POINTER)
  Property type 3 (INPUT_PROP_SEMI_MT)
Testing ... (interrupt to exit)

**Comment by 0mp** [comment]
```
Input device name: "SynPS/2 Synaptics TouchPad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value   2771
      Min     1472
      Max     5398
      Resolution      42
    Event code 1 (ABS_Y)
      Value   4268
      Min     1408
      Max     4728
      Resolution      70
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        1
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min     1472
      Max     5398
      Fuzz       8
      Resolution      42
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min     1408
      Max     4728
      Fuzz       8
      Resolution      70
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
Properties:
  Property type 0 (INPUT_PROP_POINTER)
  Property type 3 (INPUT_PROP_SEMI_MT)
```
