### ISSUE TITLE
Move data files to a data directory (#58)

### ISSUE THREAD

**Issue by 0mp** [0mp/io-touchpad#64]
At the moment the data files are scattered around the `app/` directory. We should move them to `app/classifier/data` according to this example:

```
setup.py
src/
    mypkg/
        __init__.py
        module.py
        data/
            tables.dat
            spoons.dat
            forks.dat
```

Reference: https://docs.python.org/2/distutils/setupscript.html#installing-package-data
Relates: pull request #58

**Comment by 0mp** [comment]
I thought that these files

-app/drawings-signals
- app/drawings-sizes
- app/nn-model
- app/tolerance_distance

 are some static parameters of the classifier module stored in files. 

It turns out that they change after a learning session.

I highly doubt that we should store files like these in the repository.

**Comment by michal7352** [comment]
But nn-model file and tolearance_distance files are ok? We only need to change path ?

**Comment by 0mp** [comment]
Both nn-model and tolerance distance change after the learning session. We should separate the builtin symbols from the user defined symbols.

Then the builtin symbols should be stored on the server and be rarely changed whereas the files related to the user defined symbols should ignored by git.

**Comment by michal7352** [comment]
All files change only after learning sessions.

**Comment by 0mp** [comment]
Well, then we should two have a set of read only files with a builtin, predefined symbol and a set of files for user defined symbols.

**Comment by 0mp** [comment]
BTW, take a look at the executor and databox modules. In the #68 branch.
