### ISSUE TITLE
File format change

### ISSUE THREAD

**Issue by michal7352** [0mp/io-touchpad#70]
Instead of storing symbols in two files, we could do one file and use 'pickle' library to save list of list of signals.

**Comment by 0mp** [comment]
How it affects the performance? Why would it be convenient?

**Comment by michal7352** [comment]
Shorter code for instance. And look how drawings-size file is stupid.

**Comment by 0mp** [comment]
This issues is realted: https://github.com/0mp/io-touchpad/issues/64
